/* SEARCH TWEET CONSTANTS */
export const TOGGLE_COLOR_MODE = 'TOGGLE_COLOR_MODE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const NO_MATCHES = 'NO_MATCHES';
export const TOGGLE_FILTERS = 'TOGGLE_FILTERS';
export const DATE_ERROR = 'DATE_ERROR';
export const LOADING = 'LOADING';
export const CLEAR_TWEETS = 'CLEAR_TWEETS';
export const UPDATE_CHAMPIONS = 'UPDATE_CHAMPIONS';
export const CLEAR_SCOREBOARD = 'CLEAR_SCOREBOARD';

/* STREAM TWEET CONSTANTS */
export const UPDATE_STREAM = 'UPDATE_TWEETS';
export const CLEAR_STREAM = 'CLEAR_STREAM';

/* CHESS TWEET CONSTANTS */
export const UPDATE_HISTORY = 'UPDATE_HISTORY';
export const MAKE_POLL_MOVE = 'MAKE_POLL_MOVE';
export const CLEAR_GAME = 'CLEAR_GAME';