export const TOGGLE_COLOR_MODE = 'TOGGLE_COLOR_MODE';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const NO_MATCHES = 'NO_MATCHES';
export const TOGGLE_INTERVAL = 'TOGGLE_INTERVAL';
export const DATE_ERROR = 'DATE_ERROR';